### ISSUE TITLE
感谢你提供的方法，我还有些问题想问问

### ISSUE THREAD

**Issue by CjoyHome** [xufeikko/webIm#1]
你好，我想问问这些方法要怎么引入？我看你的没有将这些引入，之引入了webim.js
![image](https://user-images.githubusercontent.com/26813427/51463821-305e4200-1d9f-11e9-820f-8424c8dabf95.png)

**Comment by xufeikko** [comment]
你用的这个是官方demo里面的文件,我这里是在vue中使用的方式，只用了部分功能，引入了webIm.js文件并用es6进行了一点改写   在使用的时候用import引入js文件就可以了 。如果是h5或jsp方式不需要使用我这种方法

**Comment by MutelyMilo** [comment]
我想问一下 您具体都实现了什么功能呢？？？可以点对点 创建聊天室？？

**Comment by CjoyHome** [comment]
是点对点
